### ISSUE TITLE
Web-page doesn't appear when BLE comes into the picture!!

### ISSUE THREAD

**Issue by Bhavikjp** [moononournation/Arduino_BLE_Scanner#3]
Hello @moononournation ,

I have used your code for my application of beacon scanning.
WiFi(Station Mode) + BLE works together without any issue.
Now I have created one web-page for WiFi configuration and for other configurations.
both mode of the WiFi (STA+AP) works fine at the same time and web-page also appear when BLE scanning code is not integrated with it.
**But when I added part of the code for BLE scanning to it, AP will be created and station mode also works properly, but web-page doesn't appear.**

So my question is, does BLE and WiFi (AP mode) works together??
If yes then, please suggest me a way to solve this issue.

**Thanks!!**

**Comment by moononournation** [comment]
Sorry for the late reply, I think it is the multitask problems. Arduino is very simple framework and only have one loop procedure, thats mean only running one thing at the same time. But since ESP32 have 2 cores, it should be able to handle 2 things at the same time. You may try to find how to put one loop to the other core. Or you can simply only scan BLE within the web request call.
