### ISSUE TITLE
Core 1 Panic

### ISSUE THREAD

**Issue by Azimuth0r** [moononournation/Arduino_BLE_Scanner#4]
I'm getting the following once I flash the code. I tried commenting out most of the code in the loop, but it looks like the issue occurs during setup.

Guru Meditation Error: Core  1 panic'ed (LoadProhibited). Exception was unhandled.
Core 1 register dump:
PC      : 0x40177562  PS      : 0x00060030  A0      : 0x800d14fd  A1      : 0x3ffdab80  
A2      : 0x00000000  A3      : 0x3ffd8d80  A4      : 0x3ffc9760  A5      : 0x80000020  
A6      : 0x00000000  A7      : 0x3ffd5864  A8      : 0x00000005  A9      : 0x00000020  
A10     : 0x00000010  A11     : 0x00000000  A12     : 0x80092c4c  A13     : 0x3ffd5720  
A14     : 0x00000003  A15     : 0x00060023  SAR     : 0x00000000  EXCCAUSE: 0x0000001c  
EXCVADDR: 0x00000150  LBEG    : 0x00000000  LEND    : 0x00000000  LCOUNT  : 0x00000000  

Backtrace: 0x40177562:0x3ffdab80 0x400d14fa:0x3ffdabc0 0x401abdee:0x3ffdacf0

Rebooting...

**Comment by Galaxy-Man** [comment]
Have sames issue here.

ets Jun  8 2016 00:22:57

rst:0xc (SW_CPU_RESET),boot:0x17 (SPI_FAST_FLASH_BOOT)
configsip: 0, SPIWP:0xee
clk_drv:0x00,q_drv:0x00,d_drv:0x00,cs0_drv:0x00,hd_drv:0x00,wp_drv:0x00
mode:DIO, clock div:1
load:0x3fff0018,len:4
load:0x3fff001c,len:808
load:0x40078000,len:6084
load:0x40080000,len:6696
entry 0x400802e4
E (525) spiram: SPI RAM enabled but initialization failed. Bailing out.
Guru Meditation Error: Core  1 panic'ed (LoadProhibited). Exception was unhandled.
Core 1 register dump:
PC      : 0x4019bd62  PS      : 0x00060030  A0      : 0x800d1835  A1      : 0x3ffdace0  
A2      : 0x00000000  A3      : 0x3ffd8f00  A4      : 0x3ffc9854  A5      : 0x80000020  
A6      : 0x00000008  A7      : 0x00000001  A8      : 0x00000005  A9      : 0x00000020  
A10     : 0x00000010  A11     : 0x00000000  A12     : 0x00000000  A13     : 0x3ffc8bbc  
A14     : 0x00000003  A15     : 0x00060023  SAR     : 0x00000000  EXCCAUSE: 0x0000001c  
EXCVADDR: 0x00000150  LBEG    : 0x00000000  LEND    : 0x00000000  LCOUNT  : 0x00000000  

Backtrace: 0x4019bd62:0x3ffdace0 0x400d1832:0x3ffdad20 0x401d023e:0x3ffdae70

Rebooting...

**Comment by Galaxy-Man** [comment]
After a bit of reading I have now found how to fix the Core 1 Panic issue.

All compiles with no errors and runs correctly in the serial monitor.

Thanks

**Comment by moononournation** [comment]
Can you share how to solve it here?

**Comment by Galaxy-Man** [comment]
Hi  Moononournation 

This is what I get on the serial monitor, is it correct??

The HTTP Error is because I do not have the backend server.

Start BLE scan for 30 seconds...
Advertised Device: Name: , Address: 4b:c3:9d:51:80:df, manufacturer data: 060001092002ad5fcb581bf8f8708ebdb9445ceaaa260e2e95cdf9219f 
Advertised Device: Name: , Address: 30:58:a9:e1:71:ae, manufacturer data: 06000109200221b020d531a993375de354bb06cbf5ae0b0d432fd5731a 
Advertised Device: Name: , Address: 3e:37:6c:85:c9:80, manufacturer data: 060001092000f9f92ba7457a59bc0bdb17fe24dc03cfd700ce54042aa6 
Advertised Device: Name: , Address: 44:09:9d:c0:0f:a1, manufacturer data: 0600010920020057880a8184f1baaa701180d0ce3a6e2f4d22b758a7fe 
Advertised Device: Name: , Address: 19:3b:be:a9:a1:3d, manufacturer data: 060001092002f4eabd0f2d9d9da39a80a752f93a519cfd7b432007f89d 
Advertised Device: Name: , Address: 32:7b:1b:5a:f0:10, manufacturer data: 060001092002ddf2c06bde9f0b84685581d5955bffd1599902356edabb 
Scan done!
WiFi Connected
Payload:
[{"Address":"19:3b:be:a9:a1:3d","Rssi":-90,"ManufacturerData":"0636333633333336333333333333333633333333333333333333333333"},{"Address":"30:58:a9:e1:71:ae","Rssi":-78,"ManufacturerData":"0636333633333336333333333333333633333333333333333333333333"},{"Address":"32:7b:1b:5a:f0:10","Rssi":-93,"ManufacturerData":"0636333633333336333333333333333633333333333333333333333333"},{"Address":"3e:37:6c:85:c9:80","Rssi":-65,"ManufacturerData":"0636333633333336333333333333333633333333333333333333333333"},{"Address":"44:09:9d:c0:0f:a1","Rssi":-63,"ManufacturerData":"0636333633333336333333333333333633333333333333333333333333"},{"Address":"4b:c3:9d:51:80:df","Rssi":-69,"ManufacturerData":"0636333633333336333333333333333633333333333333333333333333"}]
[HTTP] begin...
[HTTP] GET... failed, error: connection refused
Enter deep sleep for 300 seconds...

**Comment by Galaxy-Man** [comment]
I have used the following...  
Arduino IDE 1.8.9 Win/OSX (not Sublime DevIOT) make sure you update all boards and libraries this is important.    
Download Neil Kolban's ESP32 BLE for Arduino library and copy to arduino/libraries.  
https://github.com/nkolban/ESP32_BLE_Arduino  
Build and upload using WeMos LoLin No OTA  
That is it!  

Ianandra

**Comment by Galaxy-Man** [comment]
Hi M

My only comment is why does it not show the Advertised Device: Name?

Advertised Device: Name: , Address: 19:3b:be:a9:a1:3d, manufacturer data: 060001092002f4eabd0f2d9d9da39a80a752f93a519cfd7b432007f89d

Ianandra

**Comment by moononournation** [comment]
Hi G,

As mentioned at ESP32_BLE_Arduino page, it already included in Arduino directly, you do not need to download it.
BLE have many fields related to "name", e.g. there are 2 "localname" fields in advertising data, 0x08 and 0x09. But current BLEAdvertisedDevice class only decoded 0x09.

**Comment by skickar** [comment]
The solution sort-of provided by Galaxy-Man didn't work.

I have an endless loop of this:

ets Jun  8 2016 00:22:57

rst:0xc (SW_CPU_RESET),boot:0x13 (SPI_FAST_FLASH_BOOT)
configsip: 0, SPIWP:0xee
clk_drv:0x00,q_drv:0x00,d_drv:0x00,cs0_drv:0x00,hd_drv:0x00,wp_drv:0x00
mode:DIO, clock div:1
load:0x3fff0018,len:4
load:0x3fff001c,len:808
load:0x40078000,len:6084
load:0x40080000,len:6696
entry 0x400802e4
Guru Meditation Error: Core  1 panic'ed (LoadProhibited). Exception was unhandled.
Core 1 register dump:
PC      : 0x40199752  PS      : 0x00060030  A0      : 0x800d183d  A1      : 0x3ffdad00  
A2      : 0x00000000  A3      : 0x3ffd8f20  A4      : 0x3ffc98f4  A5      : 0x80000020  
A6      : 0x00000000  A7      : 0x3ffd59fc  A8      : 0x00000005  A9      : 0x00000020  
A10     : 0x00000010  A11     : 0x00000000  A12     : 0x80092c4c  A13     : 0x3ffd58b0  
A14     : 0x00000003  A15     : 0x00060023  SAR     : 0x00000000  EXCCAUSE: 0x0000001c  
EXCVADDR: 0x00000150  LBEG    : 0x00000000  LEND    : 0x00000000  LCOUNT  : 0x00000000  

Backtrace: 0x40199752:0x3ffdad00 0x400d183a:0x3ffdad40 0x401cdc0a:0x3ffdae80

Rebooting...
ets Jun  8 2016 00:22:57

rst:0xc (SW_CPU_RESET),boot:0x13 (SPI_FAST_FLASH_BOOT)
configsip: 0, SPIWP:0xee
clk_drv:0x00,q_drv:0x00,d_drv:0x00,cs0_drv:0x00,hd_drv:0x00,wp_drv:0x00
mode:DIO, clock div:1
load:0x3fff0018,len:4
load:0x3fff001c,len:808
load:0x40078000,len:6084
load:0x40080000,len:6696
entry 0x400802e4
Guru Meditation Error: Core  1 panic'ed (LoadProhibited). Exception was unhandled.
Core 1 register dump:
PC      : 0x40199752  PS      : 0x00060030  A0      : 0x800d183d  A1      : 0x3ffdad00  
A2      : 0x00000000  A3      : 0x3ffd8f20  A4      : 0x3ffc98f4  A5      : 0x80000020  
A6      : 0x00000000  A7      : 0x3ffd59fc  A8      : 0x00000005  A9      : 0x00000020  
A10     : 0x00000010  A11     : 0x00000000  A12     : 0x80092c4c  A13     : 0x3ffd58b0  
A14     : 0x00000003  A15     : 0x00060023  SAR     : 0x00000000  EXCCAUSE: 0x0000001c  
EXCVADDR: 0x00000150  LBEG    : 0x00000000  LEND    : 0x00000000  LCOUNT  : 0x00000000  

Backtrace: 0x40199752:0x3ffdad00 0x400d183a:0x3ffdad40 0x401cdc0a:0x3ffdae80

Rebooting...

**Comment by syalujjwal** [comment]
Facing the same problem as @skickar 

Rebooting...
ets Jun  8 2016 00:22:57

rst:0xc (SW_CPU_RESET),boot:0x13 (SPI_FAST_FLASH_BOOT)
configsip: 0, SPIWP:0xee
clk_drv:0x00,q_drv:0x00,d_drv:0x00,cs0_drv:0x00,hd_drv:0x00,wp_drv:0x00
mode:DIO, clock div:1
load:0x3fff0018,len:4
load:0x3fff001c,len:1216
ho 0 tail 12 room 4
load:0x40078000,len:9720
ho 0 tail 12 room 4
load:0x40080400,len:6352
entry 0x400806b8
Guru Meditation Error: Core  1 panic'ed (LoadProhibited). Exception was unhandled.
Core 1 register dump:
PC      : 0x40107688  PS      : 0x00060030  A0      : 0x800d1eac  A1      : 0x3ffcee00  
A2      : 0x00000000  A3      : 0x3ffbfb64  A4      : 0x8008fce0  A5      : 0x3ffba100  
A6      : 0x00000003  A7      : 0x00060823  A8      : 0x00060820  A9      : 0x00000001  
A10     : 0x00000014  A11     : 0x00000000  A12     : 0x00060023  A13     : 0x3ffba264  
A14     : 0x00000000  A15     : 0x00000000  SAR     : 0x00000000  EXCCAUSE: 0x0000001c  
EXCVADDR: 0x00000134  LBEG    : 0x00000000  LEND    : 0x00000000  LCOUNT  : 0x00000000  

Backtrace: 0x40107688:0x3ffcee00 0x400d1ea9:0x3ffcee30 0x400da9c3:0x3ffcef80 0x4008eb71:0x3ffcefa0

**Comment by konstantingoretzki** [comment]
Hi there. 
Same problem but I managed to narrow the error down with the [Exception Stack Trace Decoder](https://github.com/me-no-dev/EspExceptionDecoder).

The problem is in line 50: https://github.com/moononournation/Arduino_BLE_Scanner/blob/master/Arduino_BLE_Scanner.ino#L50

I am not an ESP32 expert but I guess it should say ```esp_wifi_start();``` and not ```..._stop();```. 
Otherwise the WiFi interface never starts and therefore inside setup at least ```wifiMulti.addAP(WIFI_SSID, WIFI_PASSWORD);``` will fail. So might be a typo?

With the fix everything works now as supposed. The device does not boot loop anymore and it connects after the scan to my AP and sends the data to my server.

Would be great if someone could test it if it works for them aswell. If so I could just do a quick pull request to fix it inside the repo, if you want to.

**Comment by moononournation** [comment]
Yes, the key point is esp_wifi_stop(). But the WiFi is stop intentionally for saving power before I need WiFi connection. However, I found the latest arduino-esp32 firmware will failed to initial BLE if I manually called stop WiFi. I have removed that line of code and everything goes well.
